import type {Gen} from '@ryanatkn/gro/gen.js';
import type {FileFilter} from '@fuzdev/fuz_util/path.js';

import {
	collect_css_classes,
	CssClasses,
	generate_classes_css,
	type CssClassDeclaration,
	type CssClassDeclarationInterpreter,
	type CssClassDiagnostic,
} from './css_class_helpers.js';
import {css_classes_by_name} from './css_classes.js';
import {css_class_interpreters} from './css_class_interpreters.js';

export interface GenFuzCssOptions {
	filter_file?: FileFilter | null;
	include_stats?: boolean;
	classes_by_name?: Record<string, CssClassDeclaration | undefined>;
	class_interpreters?: Array<CssClassDeclarationInterpreter>;
	/**
	 * How to handle CSS-literal errors during generation.
	 * - 'log' (default): Log errors, skip invalid classes, continue
	 * - 'throw': Throw on first error, fail the build
	 */
	on_error?: 'log' | 'throw';
}

/**
 * Error thrown when CSS-literal generation encounters errors and `on_error: 'throw'` is set.
 */
export class CssGenerationError extends Error {
	diagnostics: Array<CssClassDiagnostic>;

	constructor(diagnostics: Array<CssClassDiagnostic>) {
		const error_count = diagnostics.filter((d) => d.level === 'error').length;
		const message = `CSS generation failed with ${error_count} error${error_count === 1 ? '' : 's'}:\n${diagnostics
			.filter((d) => d.level === 'error')
			.map((d) => `  - ${d.class_name}: ${d.message}${d.suggestion ? ` (${d.suggestion})` : ''}`)
			.join('\n')}`;
		super(message);
		this.name = 'CssGenerationError';
		this.diagnostics = diagnostics;
	}
}

const filter_file_default: FileFilter = (path) => {
	if (path.includes('.test.') || path.includes('/test/') || path.includes('.gen.')) {
		return false;
	}
	const ext = path.slice(path.lastIndexOf('.'));
	return ext === '.svelte' || ext === '.ts' || ext === '.js';
};

export const gen_fuz_css = (options: GenFuzCssOptions = {}): Gen => {
	const {
		filter_file = filter_file_default,
		include_stats = false,
		classes_by_name = css_classes_by_name,
		class_interpreters = css_class_interpreters,
		on_error = 'log',
	} = options;

	return {
		dependencies: 'all',
		// TODO optimize, do we need to handle deleted files or removed classes though?
		// This isn't as much a problem in watch mode but isn't clean.
		// dependencies: ({changed_file_id, filer}) => {
		// 	if (!changed_file_id) return 'all';
		// 	const disknode = filer.get_by_id(changed_file_id);
		// 	if (disknode?.contents && collect_css_classes(disknode.contents).size) {
		// 		return 'all';
		// 	}
		// 	return null;
		// },
		generate: async ({filer, log, origin_path}) => {
			log.info('generating Fuz CSS classes...');

			await filer.init();

			const css_classes = new CssClasses();

			const stats = {
				total_files: filer.files.size,
				external_files: 0,
				internal_files: 0,
				processed_files: 0,
				files_with_content: 0,
				files_with_classes: 0,
			};

			for (const disknode of filer.files.values()) {
				if (disknode.external) {
					stats.external_files++;
				} else {
					stats.internal_files++;
				}

				if (filter_file && !filter_file(disknode.id)) {
					continue;
				}

				stats.processed_files++;

				if (disknode.contents !== null) {
					stats.files_with_content++;
					const classes = collect_css_classes(disknode.contents);
					if (classes.size > 0) {
						css_classes.add(disknode.id, classes);
						stats.files_with_classes++;
					}
				}
			}

			const unique_classes = new Set();
			for (const file_classes of css_classes.get().values()) {
				for (const class_name of file_classes) {
					unique_classes.add(class_name);
				}
			}

			if (include_stats) {
				log.info('File statistics:');
				log.info(`  Total files in filer: ${stats.total_files}`);
				log.info(`    External: ${stats.external_files}`);
				log.info(`    Internal: ${stats.internal_files}`);
				log.info(`  Files processed (passed filter): ${stats.processed_files}`);
				log.info(`    With content: ${stats.files_with_content}`);
				log.info(`    With CSS classes: ${stats.files_with_classes}`);
				log.info(`  Unique CSS classes found: ${unique_classes.size}`);
			}

			const result = generate_classes_css(
				css_classes.get(),
				classes_by_name,
				class_interpreters,
				log,
			);

			// Check for errors and handle based on on_error setting
			const errors = result.diagnostics.filter((d) => d.level === 'error');
			if (errors.length > 0) {
				if (on_error === 'throw') {
					throw new CssGenerationError(result.diagnostics);
				}
				// 'log' mode - errors are already logged by interpret_css_literal
				log.warn(
					`CSS generation completed with ${errors.length} error${errors.length === 1 ? '' : 's'} (invalid classes skipped)`,
				);
			}

			const banner = `generated by ${origin_path}`;

			const content_parts = [`/* ${banner} */`];

			if (include_stats) {
				const performance_note = `/* *
 * File statistics:
 * - Total files in filer: ${stats.total_files}
 * - External dependencies: ${stats.external_files}
 * - Internal project files: ${stats.internal_files}
 * - Files processed (passed filter): ${stats.processed_files}
 * - Files with CSS classes: ${stats.files_with_classes}
 * - Unique classes found: ${unique_classes.size}
 */`;
				content_parts.push(performance_note);
			}

			content_parts.push(result.css);
			content_parts.push(`/* ${banner} */`);

			return content_parts.join('\n\n');
		},
	};
};
