import type { Gen } from '@fuzdev/gro';

import { default_variables } from './variables.ts';

/**
 * Generates `scheme_adaptive_variables.ts`, the literal twin of the
 * scheme-adaptive (dual-slot) subset of `default_variables`.
 *
 * The subset is emitted as literals rather than imported so `theme_stance.ts`
 * carries no dependency on `variables.ts` - the emitter calls there defeat
 * tree-shaking, so importing any part of it pulls the whole derived variable
 * set into the consumer's bundle.
 *
 * @nodocs
 */
export const gen: Gen = ({ origin_path }) => {
	const adaptive = default_variables.filter((v) => v.dark !== undefined);

	const entries = adaptive
		.map(
			(v) =>
				`\t{ name: ${JSON.stringify(v.name)}, light: ${JSON.stringify(v.light)}, dark: ${JSON.stringify(v.dark)} }`
		)
		.join(',\n');

	return `// generated by ${origin_path} -- DO NOT EDIT DIRECTLY!

import type { StyleVariable } from './variable.ts';

/**
 * The scheme-adaptive subset of \`default_variables\`: every default that
 * carries both a light and a dark value, and therefore changes appearance
 * with the color scheme. \`resolve_theme_stance\` mirrors these so a
 * single-scheme theme shows its one appearance in both schemes.
 *
 * Literal twin of \`variables.ts\`, generated so consumers of the stance
 * mirror don't pull the full derived variable set.
 */
export const scheme_adaptive_variables: Array<StyleVariable> = [
${entries}
];
`;
};
