// generated by src/lib/scheme_adaptive_variables.gen.ts -- DO NOT EDIT DIRECTLY!

import type { StyleVariable } from './variable.ts';

/**
 * The scheme-adaptive subset of `default_variables`: every default that
 * carries both a light and a dark value, and therefore changes appearance
 * with the color scheme. `resolve_theme_stance` mirrors these so a
 * single-scheme theme shows its one appearance in both schemes.
 *
 * Literal twin of `variables.ts`, generated so consumers of the stance
 * mirror don't pull the full derived variable set.
 */
export const scheme_adaptive_variables: Array<StyleVariable> = [
	{ name: 'neutral_chroma', light: '0.024', dark: '0.025' },
	{ name: 'palette_lightness_00', light: '0.985', dark: '0.147' },
	{ name: 'palette_lightness_100', light: '0.116', dark: '0.971' },
	{ name: 'palette_lightness_curve', light: '1.15', dark: '0.76' },
	{ name: 'palette_chroma_min', light: '0.0132', dark: '0.0214' },
	{ name: 'palette_chroma_max', light: '0.106', dark: '0.1088' },
	{ name: 'palette_chroma_curve', light: '1.3', dark: '1.27' },
	{
		name: 'palette_chroma_00',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_00)), 0.0072)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_00)), 0.0254)'
	},
	{
		name: 'palette_chroma_05',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_05)), 0.021)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_05)), 0.04)'
	},
	{
		name: 'palette_chroma_10',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_10)), 0.0382)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_10)), 0.0501)'
	},
	{
		name: 'palette_chroma_20',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_20)), 0.078)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_20)), 0.0673)'
	},
	{
		name: 'palette_chroma_30',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_30)), 0.1235)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_30)), 0.0824)'
	},
	{
		name: 'palette_chroma_40',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_40)), 0.1179)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_40)), 0.0964)'
	},
	{
		name: 'palette_chroma_50',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_50)), 0.1026)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_50)), 0.1095)'
	},
	{
		name: 'palette_chroma_60',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_60)), 0.0868)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_60)), 0.122)'
	},
	{
		name: 'palette_chroma_70',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_70)), 0.0706)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_70)), 0.1189)'
	},
	{
		name: 'palette_chroma_80',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_80)), 0.054)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_80)), 0.0812)'
	},
	{
		name: 'palette_chroma_90',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_90)), 0.0372)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_90)), 0.0465)'
	},
	{
		name: 'palette_chroma_95',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_95)), 0.0286)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_95)), 0.03)'
	},
	{
		name: 'palette_chroma_100',
		light:
			'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_100)), 0.02)',
		dark: 'min(calc(var(--palette_chroma_min) + (var(--palette_chroma_max) - var(--palette_chroma_min)) * var(--chroma_shape_100)), 0.0142)'
	},
	{ name: 'shade_min', light: '#fff', dark: '#000' },
	{ name: 'shade_max', light: '#000', dark: '#fff' },
	{ name: 'shade_lightness_00', light: '0.97', dark: '0.171' },
	{ name: 'shade_lightness_100', light: '0.171', dark: '0.97' },
	{ name: 'shade_lightness_curve', light: '1.09', dark: '0.92' },
	{ name: 'fg_00', light: 'var(--darken_00)', dark: 'var(--lighten_00)' },
	{ name: 'fg_05', light: 'var(--darken_05)', dark: 'var(--lighten_05)' },
	{ name: 'fg_10', light: 'var(--darken_10)', dark: 'var(--lighten_10)' },
	{ name: 'fg_20', light: 'var(--darken_20)', dark: 'var(--lighten_20)' },
	{ name: 'fg_30', light: 'var(--darken_30)', dark: 'var(--lighten_30)' },
	{ name: 'fg_40', light: 'var(--darken_40)', dark: 'var(--lighten_40)' },
	{ name: 'fg_50', light: 'var(--darken_50)', dark: 'var(--lighten_50)' },
	{ name: 'fg_60', light: 'var(--darken_60)', dark: 'var(--lighten_60)' },
	{ name: 'fg_70', light: 'var(--darken_70)', dark: 'var(--lighten_70)' },
	{ name: 'fg_80', light: 'var(--darken_80)', dark: 'var(--lighten_80)' },
	{ name: 'fg_90', light: 'var(--darken_90)', dark: 'var(--lighten_90)' },
	{ name: 'fg_95', light: 'var(--darken_95)', dark: 'var(--lighten_95)' },
	{ name: 'fg_100', light: 'var(--darken_100)', dark: 'var(--lighten_100)' },
	{ name: 'bg_00', light: 'var(--lighten_00)', dark: 'var(--darken_00)' },
	{ name: 'bg_05', light: 'var(--lighten_05)', dark: 'var(--darken_05)' },
	{ name: 'bg_10', light: 'var(--lighten_10)', dark: 'var(--darken_10)' },
	{ name: 'bg_20', light: 'var(--lighten_20)', dark: 'var(--darken_20)' },
	{ name: 'bg_30', light: 'var(--lighten_30)', dark: 'var(--darken_30)' },
	{ name: 'bg_40', light: 'var(--lighten_40)', dark: 'var(--darken_40)' },
	{ name: 'bg_50', light: 'var(--lighten_50)', dark: 'var(--darken_50)' },
	{ name: 'bg_60', light: 'var(--lighten_60)', dark: 'var(--darken_60)' },
	{ name: 'bg_70', light: 'var(--lighten_70)', dark: 'var(--darken_70)' },
	{ name: 'bg_80', light: 'var(--lighten_80)', dark: 'var(--darken_80)' },
	{ name: 'bg_90', light: 'var(--lighten_90)', dark: 'var(--darken_90)' },
	{ name: 'bg_95', light: 'var(--lighten_95)', dark: 'var(--darken_95)' },
	{ name: 'bg_100', light: 'var(--lighten_100)', dark: 'var(--darken_100)' },
	{ name: 'border_color_lightness', light: '0.345', dark: '0.857' },
	{
		name: 'border_color_chroma',
		light: 'calc(var(--neutral_chroma) * 2.6667)',
		dark: 'calc(var(--neutral_chroma) * 2.12)'
	},
	{
		name: 'border_color_05',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 4%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 8%)'
	},
	{
		name: 'border_color_10',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 7%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 14%)'
	},
	{
		name: 'border_color_20',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 13%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 22%)'
	},
	{
		name: 'border_color_30',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 22%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 32%)'
	},
	{
		name: 'border_color_40',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 34%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 44%)'
	},
	{
		name: 'border_color_50',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 48%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 56%)'
	},
	{
		name: 'border_color_60',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 62%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 68%)'
	},
	{
		name: 'border_color_70',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 76%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 80%)'
	},
	{
		name: 'border_color_80',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 88%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 90%)'
	},
	{
		name: 'border_color_90',
		light:
			'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 96%)',
		dark: 'oklch(var(--border_color_lightness) var(--border_color_chroma) var(--hue_neutral) / 97%)'
	},
	{ name: 'text_min', light: '#fff', dark: '#000' },
	{ name: 'text_max', light: '#000', dark: '#fff' },
	{ name: 'text_lightness_00', light: '0.97', dark: '0.146' },
	{ name: 'text_lightness_100', light: '0.146', dark: '0.97' },
	{ name: 'text_lightness_curve', light: '1.19', dark: '0.87' },
	{
		name: 'selection_color',
		light:
			'oklch(var(--palette_lightness_20) calc(var(--palette_chroma_20) * var(--chroma_scale) * var(--accent_chroma_scale, 1)) var(--hue_accent) / 40%)',
		dark: 'oklch(var(--palette_lightness_80) calc(var(--palette_chroma_80) * var(--chroma_scale) * var(--accent_chroma_scale, 1)) var(--hue_accent) / 40%)'
	},
	{
		name: 'button_shadow',
		light:
			'var(--shadow_inset_bottom_xs) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_30), transparent), var(--shadow_inset_top_xs) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_30), transparent)',
		dark: 'var(--shadow_inset_top_xs) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_30), transparent), var(--shadow_inset_bottom_xs) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_30), transparent)'
	},
	{
		name: 'button_shadow_hover',
		light:
			'var(--shadow_inset_bottom_sm) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_40), transparent), var(--shadow_inset_top_sm) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_40), transparent)',
		dark: 'var(--shadow_inset_top_sm) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_40), transparent), var(--shadow_inset_bottom_sm) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_40), transparent)'
	},
	{
		name: 'button_shadow_active',
		light:
			'var(--shadow_inset_top_sm) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_40), transparent), var(--shadow_inset_bottom_sm) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_40), transparent)',
		dark: 'var(--shadow_inset_bottom_sm) color-mix(in oklab, var(--shadow_color_umbra) var(--shadow_alpha_40), transparent), var(--shadow_inset_top_sm) color-mix(in oklab, var(--shadow_color_highlight) var(--shadow_alpha_40), transparent)'
	},
	{ name: 'shadow_color_umbra', light: '#000', dark: 'oklch(0.863 0.009 var(--hue_neutral))' },
	{ name: 'shadow_color_highlight', light: 'oklch(0.955 0.003 var(--hue_neutral))', dark: '#000' },
	{
		name: 'shadow_color_glow',
		light: 'oklch(0.955 0.003 var(--hue_neutral))',
		dark: 'oklch(0.863 0.009 var(--hue_neutral))'
	},
	{
		name: 'shadow_alpha_05',
		light: 'calc(6% * var(--shadow_alpha_scale))',
		dark: 'calc(13% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_10',
		light: 'calc(10% * var(--shadow_alpha_scale))',
		dark: 'calc(19% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_20',
		light: 'calc(16% * var(--shadow_alpha_scale))',
		dark: 'calc(27% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_30',
		light: 'calc(25% * var(--shadow_alpha_scale))',
		dark: 'calc(37% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_40',
		light: 'calc(36% * var(--shadow_alpha_scale))',
		dark: 'calc(47% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_50',
		light: 'calc(50% * var(--shadow_alpha_scale))',
		dark: 'calc(59% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_60',
		light: 'calc(64% * var(--shadow_alpha_scale))',
		dark: 'calc(71% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_70',
		light: 'calc(77% * var(--shadow_alpha_scale))',
		dark: 'calc(83% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_80',
		light: 'calc(88% * var(--shadow_alpha_scale))',
		dark: 'calc(91% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_90',
		light: 'calc(96% * var(--shadow_alpha_scale))',
		dark: 'calc(98% * var(--shadow_alpha_scale))'
	},
	{
		name: 'shadow_alpha_95',
		light: 'calc(99% * var(--shadow_alpha_scale))',
		dark: 'calc(100% * var(--shadow_alpha_scale))'
	}
];
