import type {Gen} from '@fuzdev/gro';

import {default_themes} from './themes.js';
import {render_theme_style} from './theme.js';

// TODO maybe this should be `base_theme.css` or `base.css` or something,
// and we could also generate and publish the other themes --
// that would allow them to be staticly used,
// currently you'd have to pass a dynamic `theme` to `Themed`

/** @nodocs */
export const gen: Gen = ({origin_path}) => {
	const banner = `/**
 * generated by ${origin_path} -- DO NOT EDIT DIRECTLY!
 *
 * This file contains all style variables. For optimized output that includes only
 * the variables your code uses, use the Vite plugin or Gro generator instead:
 *
 *   import 'virtual:fuz.css';  // Vite plugin - recommended
 *   import './fuz.css';        // Gro generator
 *
 * Direct import of this file is for utility-only mode or non-bundled usage.
 * See: https://css.fuz.dev/docs/classes
 */`;

	const theme = default_themes[0]!;
	const theme_style = render_theme_style(theme, {
		comments: true,
		empty_default_theme: false,
		specificity: 1,
	});

	return `${banner}

		/* theme: ${theme.name} */
    ${theme_style}

    ${banner}
  `;
};
