/**
 * Vite plugin for fuz_css CSS generation.
 *
 * Uses Vite's transform hook to extract CSS classes from source files
 * as they're processed, including node_modules dependencies. In bundled
 * mode (the default) it also resolves the base reset and theme variables,
 * emitting only the rules, elements, and variables the source actually uses.
 * Generates CSS on-demand via virtual module with HMR support. In dev it
 * eagerly pre-scans project sources at server startup so the first served
 * CSS is complete (see `prescan`), and resyncs clients whose HMR socket
 * connects after a missed update.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import {defineConfig} from 'vite';
 * import jsx from 'acorn-jsx';
 * import {vite_plugin_fuz_css} from '@fuzdev/fuz_css/vite_plugin_fuz_css.ts';
 *
 * export default defineConfig({
 *   plugins: [
 *     vite_plugin_fuz_css({
 *       acorn_plugins: [jsx()],
 *     }),
 *   ],
 * });
 * ```
 *
 * @module
 */

import { normalizePath, type Logger as ViteLogger, type Plugin, type ViteDevServer } from 'vite';
import { isAbsolute, join } from 'node:path';
import { hash_blake3 } from '@fuzdev/fuz_util/hash_blake3.ts';
import { fs_search } from '@fuzdev/fuz_util/fs.ts';
import { each_concurrent } from '@fuzdev/fuz_util/async.ts';

import { format_diagnostic, CssGenerationError } from './diagnostics.ts';
import { generate_css } from './generate_css.ts';
import { create_bundled_resources } from './bundled_resources.ts';
import { extract_file_cached } from './extract_file_cached.ts';
import { merge_class_definitions } from './css_class_definitions.ts';
import { css_class_interpreters } from './css_class_interpreters.ts';
import { load_css_properties } from './css_literal.ts';
import {
	DEFAULT_CACHE_DIR,
	get_file_cache_path,
	save_cached_extraction,
	delete_cached_extraction
} from './css_cache.ts';
import { default_cache_deps } from './deps_defaults.ts';
import { filter_file_default } from './file_filter.ts';
import { CssClasses } from './css_classes.ts';
import type { StyleRuleIndex } from './style_rule_parser.ts';
import { type VariableDependencyGraph, get_all_variable_names } from './variable_graph.ts';
import { extract_css_variables } from './css_variable_utils.ts';
import type { CssClassVariableIndex } from './class_variable_index.ts';
import type { CssGeneratorBaseOptions } from './css_plugin_options.ts';

/* eslint-disable no-console */

/** Banner comment at the top and bottom of generated CSS output. */
export const FUZ_CSS_BANNER = '/* generated by vite_plugin_fuz_css */';

/**
 * Marker custom property emitted by the build-mode virtual module. Unlike a CSS
 * comment (stripped by minification) this survives into the output, so
 * `generateBundle` can locate the asset where Vite placed the virtual module's
 * CSS - the importer's globally-loaded stylesheet - and splice the generated
 * CSS in there instead of an arbitrary code-split chunk.
 */
const FUZ_CSS_PLACEHOLDER = '--fuz-css-placeholder';
/** Matches the placeholder declaration so it can be stripped from the output. */
const FUZ_CSS_PLACEHOLDER_DECL_RE = /--fuz-css-placeholder\s*:\s*1\s*;?/g;
/**
 * Matches the empty `:root{}` rule left behind after stripping a solo
 * placeholder declaration. When a minifier merged the marker into a `:root`
 * block with real properties, the block isn't empty after the strip and this
 * leaves it alone.
 */
const FUZ_CSS_PLACEHOLDER_EMPTY_ROOT_RE = /:root\s*\{\s*\}/;

const VIRTUAL_ID = 'virtual:fuz.css';
/**
 * Resolved id of the virtual module, in both dev and build - a leading-slash
 * path ending in `.css`, deliberately *not* a `\0`-prefixed virtual id.
 *
 * Two properties matter:
 * - The `.css` extension makes Vite and frameworks treat the module as CSS
 *   (it passes Vite's `isCSSRequest`). In dev, Vite's CSS pipeline injects it
 *   client-side with HMR, and SvelteKit's dev FOUC-prevention inlines it into
 *   the SSR'd `<head>` so the first paint is already styled.
 * - The plain URL (no `\0`) is what makes that inlining actually happen. A
 *   `\0` id is encoded as `/@id/__x00__virtual:fuz.css` in the import graph,
 *   and SvelteKit looks deps up by URL via `moduleGraph.getModuleByUrl()`,
 *   which can't resolve the `__x00__`-encoded form back to its node - so a `\0`
 *   id is silently skipped and the page flashes unstyled on every refresh.
 *
 * This mirrors UnoCSS's `/__uno.css`. `resolveId` claims both the
 * `virtual:fuz.css` specifier and this resolved id (so re-resolution of
 * `?inline`/`?direct` query variants stays ours rather than hitting the
 * filesystem).
 */
const RESOLVED_VIRTUAL_ID = '/__fuz.css';

/**
 * Skip cache on CI (no point writing cache that won't be reused).
 */
const is_ci = !!process.env.CI;

/**
 * Debounce delay for HMR updates in milliseconds.
 *
 * Short delay to batch rapid file changes (e.g., save-all, rename operations)
 * into a single CSS regeneration. 10ms is enough to catch rapid sequential
 * saves while being imperceptible to users.
 */
const HMR_DEBOUNCE_MS = 10;

/**
 * Concurrency for the dev pre-scan (file read + cache read + extract).
 * Matches the Gro generator's default - the value controls I/O interleaving,
 * not CPU parallelism (AST parsing is synchronous on the main thread).
 */
const PRESCAN_CONCURRENCY = 8;

/** Default directories scanned by the dev pre-scan, relative to the Vite root. */
const PRESCAN_ROOTS_DEFAULT = ['src'];

/**
 * Options for the fuz_css Vite plugin.
 * Extends the shared base options with Vite-specific options.
 */
export interface VitePluginFuzCssOptions extends CssGeneratorBaseOptions {
	/**
	 * Dev-only eager pre-scan of source files at server startup.
	 *
	 * Extraction state accumulates from Vite's transform hook, so without a
	 * pre-scan the first CSS served on a cold start includes only the files
	 * the module graph happened to visit first - classes from modules the SSR
	 * walk never reaches (client-only branches, dynamic imports) are missing
	 * until a corrective HMR update, which is dropped when the browser hasn't
	 * connected yet. The pre-scan extracts every file passing `filter_file`
	 * under the given directories before the virtual module is first served,
	 * so the initial CSS is complete. Warm starts are cheap via the extraction
	 * cache.
	 *
	 * `true` scans `src` under the Vite root; `false` disables; an array gives
	 * custom directories (resolved against the Vite root unless absolute).
	 * node_modules deps are never pre-scanned - they stream in via transform
	 * and are covered by the connect-time resync.
	 *
	 * @default true
	 */
	prescan?: boolean | Array<string>;
}

/**
 * Creates the fuz_css Vite plugin.
 *
 * Extracts CSS classes from source files during Vite's transform phase
 * and generates optimized CSS via the `virtual:fuz.css` virtual module.
 */
export const vite_plugin_fuz_css = (options: VitePluginFuzCssOptions = {}): Plugin => {
	const {
		filter_file = filter_file_default,
		class_definitions: user_class_definitions,
		include_default_classes = true,
		class_interpreters = css_class_interpreters,
		additional_classes,
		exclude_classes,
		acorn_plugins,
		on_error = is_ci ? 'throw' : 'log',
		on_warning = 'log',
		cache_dir = DEFAULT_CACHE_DIR,
		base_css,
		variables,
		theme,
		additional_elements,
		additional_variables,
		exclude_elements,
		exclude_variables,
		deps = default_cache_deps,
		prescan = true
	} = options;

	// Derive include flags from null check
	const include_base = base_css !== null;
	const include_theme = variables !== null;

	// Merge class definitions (validates that definitions exist when needed)
	const all_class_definitions = merge_class_definitions(
		user_class_definitions,
		include_default_classes
	);

	// Convert to Sets for efficient lookup
	const include_set = additional_classes ? new Set(additional_classes) : null;
	const exclude_set = exclude_classes ? new Set(exclude_classes) : null;

	// Plugin state
	const css_classes = new CssClasses(include_set, exclude_set);
	const hashes: Map<string, string> = new Map();
	/** CSS variables detected per file via simple regex scan (filtered against theme) */
	const detected_variables_by_file: Map<string, Set<string>> = new Map();
	let virtual_module_loaded = false;
	/**
	 * Every resolved virtual-module id `load()` has served - the bare
	 * `/__fuz.css` plus each query variant (`?inline`/`?direct`/`?used`). HMR must
	 * invalidate *all* of them: SvelteKit's dev SSR FOUC-inlining reads
	 * `/__fuz.css?inline`, a module Vite caches separately from the bare id, so
	 * invalidating only the bare id leaves the inlined `<head>` CSS frozen at its
	 * first read and reloads keep serving stale styles.
	 */
	const loaded_virtual_ids: Set<string> = new Set();
	let is_dev = false;
	let server: ViteDevServer | null = null;
	let logger: ViteLogger | null = null;
	let css_properties: Set<string> | null = null;
	let resolved_cache_dir: string | null = null;
	let project_root: string | null = null;
	let hmr_timeout: ReturnType<typeof setTimeout> | null = null;
	let last_generated_css: string | null = null;
	let pending_css: string | null = null; // CSS generated during HMR, reused by load()
	let last_served_css: string | null = null; // last CSS returned by load(); connect-time resync diffs against it
	let prescan_promise: Promise<void> | null = null; // load() awaits this so the first served CSS is complete
	/** Suppresses per-file HMR invalidation while the pre-scan runs (it invalidates once at the end). */
	let prescan_active = false;
	/**
	 * Per-file epoch guarding against a deletion (or newer ingest) racing an
	 * in-flight ingest. `ingest_file` awaits the disk cache read; an `unlink`
	 * arriving during that await deletes the entry, but the resolved await would
	 * otherwise re-add it and resurrect the deleted file. Captured before the
	 * await, re-checked after.
	 */
	const transform_epochs: Map<string, number> = new Map();
	let epoch_seq = 0;

	/**
	 * Records every `var(--*)` reference in a file via regex scan. Stored unfiltered;
	 * `render_css` narrows to theme variables once `variable_graph` is loaded.
	 *
	 * Filtering here (the old behavior) silently dropped detections from any file
	 * transformed before the graph loads - and the graph loads asynchronously
	 * (eagerly at `configureServer` in dev, on the first `load()` in build).
	 * In SvelteKit dev, route nodes (e.g. `+page.svelte`) are resolved, and
	 * thus transformed, during SSR *before* the layout's `virtual:fuz.css` import
	 * triggers that first `load()`; a theme `var()` used only there was dropped, and
	 * the cached content hash meant it never re-scanned until the file was edited.
	 */
	const update_detected_variables = (id: string, code: string): void => {
		const file_vars = extract_css_variables(code);
		if (file_vars.size > 0) {
			detected_variables_by_file.set(id, file_vars);
		} else {
			detected_variables_by_file.delete(id);
		}
	};

	// Bundled CSS resources (when bundled mode is enabled: started eagerly at
	// configureServer in dev, lazily on first load() in build)
	let style_rule_index: StyleRuleIndex | null = null;
	let variable_graph: VariableDependencyGraph | null = null;
	let class_variable_index: CssClassVariableIndex | null = null;

	// Promise for in-flight resource loading (prevents duplicate loads)
	let bundled_resources_promise: Promise<void> | null = null;

	/** Ensures bundled CSS resources are loaded. Safe to call multiple times. */
	const ensure_bundled_resources = async (): Promise<void> => {
		if (style_rule_index !== null) return; // Already loaded
		if (bundled_resources_promise) {
			await bundled_resources_promise; // Wait for in-flight loading
			return;
		}
		bundled_resources_promise = (async () => {
			const resources = await create_bundled_resources({
				base_css,
				variables,
				theme,
				class_definitions: all_class_definitions,
				deps
			});
			style_rule_index = resources.style_rule_index;
			variable_graph = resources.variable_graph;
			class_variable_index = resources.class_variable_index;
		})();
		await bundled_resources_promise;
	};

	const log_warn = (msg: string): void => {
		if (logger) {
			logger.warn(msg);
		} else {
			console.warn(msg);
		}
	};

	const log_error = (msg: string): void => {
		if (logger) {
			logger.error(msg);
		} else {
			console.error(msg);
		}
	};

	const log_info = (msg: string): void => {
		if (logger) {
			logger.info(msg);
		} else {
			console.log(msg);
		}
	};

	/**
	 * Generates banner-wrapped CSS from the current classes, dispatching
	 * diagnostics per the `on_error`/`on_warning` settings.
	 */
	const render_css = (): string => {
		const {
			all_classes,
			all_classes_with_locations,
			explicit_classes,
			all_elements,
			explicit_elements,
			explicit_variables
		} = css_classes.get_all();

		// Aggregate per-file `var(--*)` references (stored unfiltered by
		// `update_detected_variables`) and narrow to theme variables - non-theme refs
		// may be user-defined and have no definition to emit. The graph is loaded at
		// every render-time call site (`load()`/HMR/`generateBundle` all run after
		// `ensure_bundled_resources`); when it isn't (utility-only mode), variables
		// aren't emitted anyway. `generate_css` merges in `explicit_variables`.
		const theme_var_names = variable_graph ? get_all_variable_names(variable_graph) : null;
		const detected_css_variables: Set<string> = new Set();
		if (theme_var_names) {
			for (const vars of detected_variables_by_file.values()) {
				for (const v of vars) {
					if (theme_var_names.has(v)) {
						detected_css_variables.add(v);
					}
				}
			}
		}

		const { css: final_css, diagnostics: all_diagnostics } = generate_css({
			all_classes,
			all_classes_with_locations,
			explicit_classes,
			all_elements,
			explicit_elements,
			explicit_variables,
			extraction_diagnostics: css_classes.get_diagnostics(),
			detected_css_variables,
			class_definitions: all_class_definitions,
			interpreters: class_interpreters,
			css_properties,
			include_base,
			include_theme,
			has_theme: theme != null,
			// Resources load lazily; null until ready falls back to utility-only.
			resources:
				style_rule_index && variable_graph && class_variable_index
					? { style_rule_index, variable_graph, class_variable_index }
					: null,
			additional_elements,
			additional_variables,
			exclude_elements,
			exclude_variables
		});

		// Separate errors and warnings
		const errors = all_diagnostics.filter((d) => d.level === 'error');
		const warnings = all_diagnostics.filter((d) => d.level === 'warning');

		// Handle warnings based on on_warning setting
		if (warnings.length > 0) {
			if (on_warning === 'throw') {
				throw new CssGenerationError(warnings);
			} else if (on_warning === 'log') {
				for (const warning of warnings) {
					log_warn(`[fuz_css] ${format_diagnostic(warning)}`);
				}
			}
			// 'ignore' - do nothing
		}

		// Handle errors based on on_error setting
		if (errors.length > 0) {
			if (on_error === 'throw') {
				throw new CssGenerationError(errors);
			}
			for (const error of errors) {
				log_error(`[fuz_css] ${format_diagnostic(error)}`);
			}
		}

		return `${FUZ_CSS_BANNER}\n\n${final_css}\n\n${FUZ_CSS_BANNER}`;
	};

	/**
	 * Invalidates every served virtual-module variant and pushes the js-update
	 * that makes connected clients refetch. Shared by the debounced HMR path
	 * and the connect-time resync.
	 */
	const invalidate_and_push = (new_css: string): void => {
		// Deliberately not updating last_served_css: only load() marks CSS as
		// served, so if the pushed js-update never causes a refetch, the next
		// ws connection re-diffs against what clients actually hold and pushes
		// again - convergence relies on that refetch loop.
		last_generated_css = new_css;
		pending_css = new_css; // Store for reuse in load() to avoid regenerating

		// Invalidate every served variant, not just the bare id. The bare
		// `/__fuz.css` backs the client `<style>` and gets a `js-update` so Vite
		// re-runs `updateStyle` with fresh content live. The `?inline`/`?direct`/
		// `?used` variants have no client HMR boundary - they're read fresh by the
		// next SSR render - so invalidating their cached module is enough; without
		// it, SvelteKit keeps inlining stale `<head>` CSS on every reload.
		const bare = server!.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
		if (bare) {
			server!.moduleGraph.invalidateModule(bare);
			// Vite wraps the CSS module so it self-accepts (`import.meta.hot.accept()`),
			// re-running `updateStyle` with fresh content on a `js-update`. The module's
			// plain URL is its own id (no `\0` encoding), so it doubles as the HMR path.
			server!.hot.send({
				type: 'update',
				updates: [
					{
						type: 'js-update',
						path: RESOLVED_VIRTUAL_ID,
						acceptedPath: RESOLVED_VIRTUAL_ID,
						timestamp: Date.now()
					}
				]
			});
		}
		for (const vid of loaded_virtual_ids) {
			if (vid === RESOLVED_VIRTUAL_ID) continue; // bare handled above
			const variant = server!.moduleGraph.getModuleById(vid);
			if (variant) {
				server!.moduleGraph.invalidateModule(variant);
			}
		}
	};

	/**
	 * Invalidates the virtual module and triggers HMR.
	 * Debounced to avoid spamming updates when multiple files change rapidly.
	 * Only triggers if the generated CSS actually changed.
	 */
	const invalidate_virtual_module = (): void => {
		if (!server) return;

		// Skip HMR if bundled resources aren't loaded yet - in dev they load
		// eagerly at configureServer, in build lazily on the first load() call;
		// either way the eventual load regenerates the CSS
		if ((include_base || include_theme) && style_rule_index === null) {
			return;
		}

		if (hmr_timeout) {
			clearTimeout(hmr_timeout);
		}
		hmr_timeout = setTimeout(() => {
			hmr_timeout = null;

			// Check if CSS actually changed
			const new_css = render_css();
			if (new_css === last_generated_css) {
				return; // No change, skip HMR
			}
			invalidate_and_push(new_css);
		}, HMR_DEBOUNCE_MS);
	};

	/**
	 * Ingests one file into extraction state: content-hash short-circuit,
	 * cache-aware extraction, then classes/variables/hash updates and the
	 * fire-and-forget cache write. Shared by `transform()` and the dev
	 * pre-scan. The per-file epoch guard drops this ingest's result when a
	 * deletion or a newer ingest for the same file races the awaited cache
	 * read.
	 */
	const ingest_file = async (id: string, code: string): Promise<void> => {
		// Compute content hash; skip if unchanged
		const hash = hash_blake3(code);
		if (hashes.get(id) === hash) {
			return;
		}

		const cache_path =
			!is_ci && resolved_cache_dir && project_root
				? get_file_cache_path(id, resolved_cache_dir, project_root)
				: null;

		// Capture an epoch before the (awaiting) cache read so a deletion or
		// newer ingest racing the await can be detected after it resolves.
		const epoch = ++epoch_seq;
		transform_epochs.set(id, epoch);

		const { extraction, from_cache, cache_path_to_write } = await extract_file_cached({
			deps,
			content: code,
			content_hash: hash,
			cache_path,
			filename: id,
			acorn_plugins
		});

		// Bail if the file was deleted or re-ingested during the cache read;
		// re-adding here would resurrect a deleted or stale entry.
		if (transform_epochs.get(id) !== epoch) {
			return;
		}

		// Log extraction diagnostics (only when freshly parsed; cached diagnostics
		// were already logged on the miss that produced them).
		if (!from_cache && extraction.diagnostics) {
			for (const d of extraction.diagnostics) {
				const loc = `${d.location.file}:${d.location.line}:${d.location.column}`;
				const msg = `[fuz_css] ${loc}: ${d.message}`;
				if (d.level === 'error') {
					log_error(msg);
				} else if (on_warning === 'log') {
					log_warn(msg);
				}
				// 'ignore' and 'throw' (handled at generation time) - don't log here
			}
		}

		// Update CssClasses
		css_classes.add(id, extraction);
		update_detected_variables(id, code);
		hashes.set(id, hash);

		// Save to cache (fire and forget - don't block)
		if (cache_path_to_write) {
			save_cached_extraction(deps, cache_path_to_write, hash, extraction).catch(() => {
				// Ignore cache errors
			});
		}

		// Trigger HMR if the virtual module was already served; suppressed
		// during the pre-scan, which invalidates once at the end instead of
		// re-rendering per file.
		if (virtual_module_loaded && !prescan_active) {
			invalidate_virtual_module();
		}
	};

	/**
	 * Dev-only eager scan: extracts every matching file under the configured
	 * roots before the virtual module is first served, so the initial CSS is
	 * complete - including classes from modules the SSR walk never reaches.
	 * `load()` awaits the returned promise. See the `prescan` option.
	 */
	const run_prescan = async (): Promise<void> => {
		const started = performance.now();
		const roots = Array.isArray(prescan) ? prescan : PRESCAN_ROOTS_DEFAULT;
		const found = await Promise.all(
			roots.map((root) =>
				fs_search(isAbsolute(root) ? root : join(project_root!, root), {
					file_filter: filter_file,
					sort: null
				})
			)
		);
		// Normalize to Vite's posix-style ids so pre-scan entries share keys
		// with transform ingests (`hashes`, deletion handling) on every platform.
		const file_ids = found.flat().map((p) => normalizePath(p.id));
		prescan_active = true;
		try {
			await each_concurrent(file_ids, PRESCAN_CONCURRENCY, async (id) => {
				// Per-file isolation: `each_concurrent` is fail-fast, so an uncaught
				// throw (a custom deps or acorn plugin, not parse errors - those
				// become diagnostics) would silently skip every remaining file;
				// transform() ingests independently and this matches that.
				try {
					// Reads disk bytes while transform later receives Vite's input for
					// the same id; with enforce: 'pre' those are identical, so the
					// content-hash short-circuit makes the second ingest a no-op. A
					// loader that rewrites content before 'pre' plugins would extract
					// twice, with the transform result winning - harmless, just noted.
					const r = await deps.read_text({ path: id });
					if (!r.ok) return; // deleted mid-scan or unreadable; transform covers it if it reappears
					await ingest_file(id, r.value);
				} catch (error) {
					log_error(`[fuz_css] pre-scan failed to extract ${id}: ${error}`);
				}
			});
		} finally {
			prescan_active = false;
		}
		// Every load() awaits the pre-scan, so nothing incomplete was served;
		// this is a cheap no-op-diffed safety for suppressed mid-scan transforms.
		if (virtual_module_loaded) {
			invalidate_virtual_module();
		}
		const elapsed = Math.round(performance.now() - started);
		log_info(`[fuz_css] pre-scanned ${file_ids.length} files in ${elapsed}ms`);
	};

	return {
		name: 'vite-plugin-fuz-css',
		// Run before other plugins (like Svelte) to see original source files
		enforce: 'pre',

		configResolved(resolved_config) {
			const root = resolved_config.root;
			project_root = root.endsWith('/') ? root : root + '/';
			resolved_cache_dir = join(root, cache_dir);
			logger = resolved_config.logger;
			is_dev = resolved_config.command === 'serve';
		},

		configureServer(dev_server) {
			server = dev_server;

			// Start bundled-resource loading now instead of at the first load() -
			// it overlaps with the pre-scan and the framework's own startup,
			// taking the base-CSS parse off the first request's critical path.
			// Errors are swallowed here: load() awaits the same cached promise
			// and surfaces the same error at request time.
			if (include_base || include_theme) {
				ensure_bundled_resources().catch(() => {
					// Surfaced by load() awaiting the same cached promise
				});
			}

			// Eager pre-scan (dev only): seed extraction state before the first
			// CSS serve. load() awaits this promise.
			if (prescan !== false) {
				prescan_promise = run_prescan().catch((error) => {
					log_error(`[fuz_css] pre-scan failed: ${error}`);
				});
			}

			// Connect-time resync: a client that loaded the page while extraction
			// was still discovering files (late dep transforms, dynamic imports)
			// may have missed the corrective HMR update - updates are dropped when
			// no socket is connected. When its socket opens, re-check and push if
			// the CSS moved past what load() served.
			dev_server.ws.on('connection', () => {
				if (!virtual_module_loaded || last_served_css === null) return;
				if ((include_base || include_theme) && style_rule_index === null) return;
				// Fast path: any state change schedules the debounce timer, so no
				// pending timer plus generated == served proves there's nothing to
				// push - skip the render (the common case for every new tab).
				if (hmr_timeout === null && last_generated_css === last_served_css) return;
				const css = render_css();
				if (css !== last_served_css) {
					invalidate_and_push(css);
				}
			});

			// Handle file deletion - watcher 'unlink' event
			dev_server.watcher.on('unlink', (raw_file) => {
				// chokidar reports platform paths - normalize so the key matches the
				// transform/prescan ingests (`hashes`, `transform_epochs`)
				const file = normalizePath(raw_file);
				// Invalidate any in-flight transform for this file so its post-await
				// re-add can't resurrect the deleted entry.
				transform_epochs.delete(file);
				if (hashes.has(file)) {
					css_classes.delete(file);
					hashes.delete(file);
					detected_variables_by_file.delete(file);

					// Delete cache file (fire and forget)
					if (!is_ci && resolved_cache_dir && project_root) {
						const cache_path = get_file_cache_path(file, resolved_cache_dir, project_root);
						delete_cached_extraction(deps, cache_path).catch(() => {
							// Ignore cache deletion errors
						});
					}

					if (virtual_module_loaded) {
						invalidate_virtual_module();
					}
				}
			});

			// Clean up pending timeout on server close; `httpServer` is null in
			// middleware mode, where buildEnd() below covers it
			dev_server.httpServer?.on('close', () => {
				if (hmr_timeout) {
					clearTimeout(hmr_timeout);
					hmr_timeout = null;
				}
			});
		},

		async buildStart() {
			// Load CSS properties for literal-class validation during render_css()
			css_properties = await load_css_properties();
			// Note: Bundled CSS resources (style_rule_index, variable_graph, class_variable_index)
			// load via ensure_bundled_resources() - started eagerly in configureServer
			// (dev), or lazily on the first load() call (build)
		},

		buildEnd() {
			// Vite calls this when the dev server closes too - the reliable cleanup
			// in middleware mode, where there's no owned httpServer to listen to
			if (hmr_timeout) {
				clearTimeout(hmr_timeout);
				hmr_timeout = null;
			}
		},

		resolveId(id) {
			if (id === VIRTUAL_ID) {
				return RESOLVED_VIRTUAL_ID;
			}
			// Claim the resolved id (and its `?inline`/`?direct`/`?used` query
			// variants) so re-resolution stays ours instead of hitting the
			// filesystem - SvelteKit's dev SSR inlining loads `/__fuz.css?inline`.
			if (id.split('?', 1)[0] === RESOLVED_VIRTUAL_ID) {
				return id;
			}
			return undefined;
		},

		async load(id) {
			// Match the base id and any query variant (`?inline`, `?direct`, `?used`)
			// Vite or SvelteKit appends - SvelteKit's dev SSR inlining loads `?inline`.
			if (id.split('?', 1)[0] !== RESOLVED_VIRTUAL_ID) {
				return undefined;
			}
			virtual_module_loaded = true;
			loaded_virtual_ids.add(id); // bare + each `?inline`/`?direct`/`?used` variant, for HMR invalidation
			// Ensure resources are ready (started eagerly in dev, lazily here in
			// build); in dev also wait for the pre-scan so the first served CSS
			// is complete.
			const pending: Array<Promise<void>> = [];
			if (include_base || include_theme) {
				pending.push(ensure_bundled_resources());
			}
			if (prescan_promise) {
				pending.push(prescan_promise);
			}
			if (pending.length > 0) {
				await Promise.all(pending);
			}
			if (is_dev) {
				// Dev: return real CSS. Vite's CSS pipeline wraps it for client-side
				// injection with HMR, and SvelteKit's dev SSR inlines it into the
				// document `<head>` so the first paint is styled (no FOUC on refresh).
				// Reuse CSS computed during an HMR pass when available.
				const css = pending_css ?? render_css();
				pending_css = null;
				last_generated_css = css; // Track for HMR diffing
				last_served_css = css; // Track for connect-time resync
				return css;
			}
			// Build: emit a marker rule (not a comment - comments are minified away)
			// so generateBundle can find the importer's CSS asset (loaded on every
			// page) and splice the full generated CSS in there.
			return `:root{${FUZ_CSS_PLACEHOLDER}:1}`;
		},

		generateBundle(_options, bundle) {
			// Regenerate CSS with all extracted classes. Runs after all transforms,
			// so the full set of used classes is available.
			const generated_css = render_css();

			// Splice the generated CSS into the asset that holds the virtual module's
			// placeholder marker. Vite places that marker in the CSS of whatever
			// imported `virtual:fuz.css` (typically the root layout/entry), which is
			// loaded on every page. Appending to an arbitrary "first" CSS asset
			// instead breaks code-split builds (e.g. SvelteKit's per-route CSS):
			// pages that don't load that chunk render completely unstyled.
			let spliced_count = 0;
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css') &&
					chunk.source.includes(FUZ_CSS_PLACEHOLDER)
				) {
					chunk.source =
						chunk.source
							.replace(FUZ_CSS_PLACEHOLDER_DECL_RE, '')
							.replace(FUZ_CSS_PLACEHOLDER_EMPTY_ROOT_RE, '') +
						'\n' +
						generated_css;
					spliced_count++;
				}
			}

			// Normal path: exactly one marked asset, loaded on every page.
			if (spliced_count === 1) return;

			// Marker landed in more than one asset - the full CSS is now duplicated
			// across them. Functional but bloated; surface it rather than ship silently.
			if (spliced_count > 1) {
				log_error(
					`[fuz_css] placeholder marker found in ${spliced_count} CSS assets; generated CSS is` +
						` duplicated across them. Expected a single globally-loaded asset.`
				);
				return;
			}

			// spliced_count === 0 below: the marker is gone. Only act when the virtual
			// module was actually imported and there's real CSS to deliver - otherwise
			// there's nothing to place (e.g. plugin installed but `virtual:fuz.css`
			// never imported, or a fully empty generation that's only banners).
			if (!virtual_module_loaded) return;
			const has_real_css = generated_css.replaceAll(FUZ_CSS_BANNER, '').trim().length > 0;
			if (!has_real_css) return;

			let css_asset_count = 0;
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css')
				) {
					css_asset_count++;
				}
			}

			// `virtual:fuz.css` was imported but there's nowhere to place its output -
			// every page would render completely unstyled. Fail the build rather than
			// ship a broken artifact (e.g. a config that inlines CSS into JS chunks,
			// where the marker rides in a chunk these asset checks skip).
			if (css_asset_count === 0) {
				throw new Error(
					'[fuz_css] virtual:fuz.css was imported but no CSS asset exists to hold the generated' +
						' styles - every page would be unstyled. Check the build config (cssCodeSplit /' +
						' CSS-in-JS inlining).'
				);
			}

			// Marker stripped but CSS assets exist (e.g. a minifier pruned the unused
			// custom property): append to every one so styles are present on every
			// page. Output may be duplicated; this is a degraded path, so surface it.
			log_error(
				`[fuz_css] placeholder marker not found in any CSS asset (likely stripped by a CSS` +
					` minifier); appending generated CSS to all ${css_asset_count} CSS assets as a` +
					` fallback. Output may be duplicated.`
			);
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css')
				) {
					chunk.source = chunk.source + '\n' + generated_css;
				}
			}
		},

		async transform(code, id) {
			// Skip non-matching files
			if (!filter_file(id)) {
				return null;
			}

			await ingest_file(id, code);

			return null;
		}

		// Note: handleHotUpdate not needed - transform hook handles file changes,
		// and configureServer's watcher.on('unlink') handles file deletion
	};
};
