/**
 * Vite plugin for fuz_css utility class generation.
 *
 * Uses Vite's transform hook to extract CSS classes from source files
 * as they're processed, including node_modules dependencies.
 * Generates CSS on-demand via virtual module with HMR support.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import {defineConfig} from 'vite';
 * import jsx from 'acorn-jsx';
 * import {vite_plugin_fuz_css} from '@fuzdev/fuz_css/vite_plugin_fuz_css.js';
 *
 * export default defineConfig({
 *   plugins: [
 *     vite_plugin_fuz_css({
 *       acorn_plugins: [jsx()],
 *     }),
 *   ],
 * });
 * ```
 *
 * @module
 */

import type {Logger as ViteLogger, Plugin, ViteDevServer} from 'vite';
import {join} from 'node:path';
import {hash_blake3} from '@fuzdev/fuz_util/hash_blake3.js';

import {format_diagnostic, CssGenerationError} from './diagnostics.js';
import {generate_css} from './generate_css.js';
import {create_bundled_resources} from './bundled_resources.js';
import {extract_file_cached} from './extract_file_cached.js';
import {merge_class_definitions} from './css_class_definitions.js';
import {css_class_interpreters} from './css_class_interpreters.js';
import {load_css_properties} from './css_literal.js';
import {
	DEFAULT_CACHE_DIR,
	get_file_cache_path,
	save_cached_extraction,
	delete_cached_extraction,
} from './css_cache.js';
import {default_cache_deps} from './deps_defaults.js';
import {filter_file_default} from './file_filter.js';
import {CssClasses} from './css_classes.js';
import type {StyleRuleIndex} from './style_rule_parser.js';
import {type VariableDependencyGraph, get_all_variable_names} from './variable_graph.js';
import {extract_css_variables} from './css_variable_utils.js';
import type {CssClassVariableIndex} from './class_variable_index.js';
import type {CssGeneratorBaseOptions} from './css_plugin_options.js';

/* eslint-disable no-console */

/** Banner comment at the top and bottom of generated CSS output. */
export const FUZ_CSS_BANNER = '/* generated by vite_plugin_fuz_css */';

/**
 * Marker custom property emitted by the build-mode virtual module. Unlike a CSS
 * comment (stripped by minification) this survives into the output, so
 * `generateBundle` can locate the asset where Vite placed the virtual module's
 * CSS — the importer's globally-loaded stylesheet — and splice the generated
 * CSS in there instead of an arbitrary code-split chunk.
 */
const FUZ_CSS_PLACEHOLDER = '--fuz-css-placeholder';
/** Matches the placeholder declaration so it can be stripped from the output. */
const FUZ_CSS_PLACEHOLDER_DECL_RE = /--fuz-css-placeholder\s*:\s*1\s*;?/g;
/**
 * Matches the empty `:root{}` rule left behind after stripping a solo
 * placeholder declaration. When a minifier merged the marker into a `:root`
 * block with real properties, the block isn't empty after the strip and this
 * leaves it alone.
 */
const FUZ_CSS_PLACEHOLDER_EMPTY_ROOT_RE = /:root\s*\{\s*\}/;

const VIRTUAL_ID = 'virtual:fuz.css';
// In dev mode, resolve to .js so Vite treats it as JS (for HMR handling)
// In build mode, resolve to .css for proper CSS bundling
const RESOLVED_VIRTUAL_ID_JS = '\0virtual:fuz.css.js';
const RESOLVED_VIRTUAL_ID_CSS = '\0virtual:fuz.css';

// TODO investigate: Dev mode uses a JS wrapper that injects CSS and self-accepts HMR.
// We couldn't get plain CSS with `css-update` to work for virtual modules - there's a
// mismatch between `data-vite-dev-id` (set to `\0virtual:fuz.css`) and the importable
// URL (`/@id/__x00__virtual:fuz.css`). UnoCSS uses `js-update` with `mod.url` for plain
// CSS but that broke all HMR when we tried it. Areas to investigate:
// - How does Vite's CSS HMR actually resolve virtual module URLs?
// - Why does UnoCSS's approach work for them but not here?
// - Is there a way to control what `data-vite-dev-id` gets set to?
// The current JS wrapper approach works reliably, but plain CSS would be cleaner.

/**
 * Skip cache on CI (no point writing cache that won't be reused).
 */
const is_ci = !!process.env.CI;

/**
 * Debounce delay for HMR updates in milliseconds.
 *
 * Short delay to batch rapid file changes (e.g., save-all, rename operations)
 * into a single CSS regeneration. 10ms is enough to catch rapid sequential
 * saves while being imperceptible to users.
 */
const HMR_DEBOUNCE_MS = 10;

/**
 * Options for the fuz_css Vite plugin.
 * Extends the shared base options (no additional Vite-specific options currently needed).
 */

export interface VitePluginFuzCssOptions extends CssGeneratorBaseOptions {}

/**
 * Creates the fuz_css Vite plugin.
 *
 * Extracts CSS classes from source files during Vite's transform phase
 * and generates optimized CSS via the `virtual:fuz.css` virtual module.
 */
export const vite_plugin_fuz_css = (options: VitePluginFuzCssOptions = {}): Plugin => {
	const {
		filter_file = filter_file_default,
		class_definitions: user_class_definitions,
		include_default_classes = true,
		class_interpreters = css_class_interpreters,
		additional_classes,
		exclude_classes,
		acorn_plugins,
		on_error = is_ci ? 'throw' : 'log',
		on_warning = 'log',
		cache_dir = DEFAULT_CACHE_DIR,
		base_css,
		variables,
		theme_specificity = 1,
		additional_elements,
		additional_variables,
		exclude_elements,
		exclude_variables,
		deps = default_cache_deps,
	} = options;

	// Derive include flags from null check
	const include_base = base_css !== null;
	const include_theme = variables !== null;

	// Merge class definitions (validates that definitions exist when needed)
	const all_class_definitions = merge_class_definitions(
		user_class_definitions,
		include_default_classes,
	);

	// Convert to Sets for efficient lookup
	const include_set = additional_classes ? new Set(additional_classes) : null;
	const exclude_set = exclude_classes ? new Set(exclude_classes) : null;

	// Plugin state
	const css_classes = new CssClasses(include_set, exclude_set);
	const hashes: Map<string, string> = new Map();
	/** CSS variables detected per file via simple regex scan (filtered against theme) */
	const detected_variables_by_file: Map<string, Set<string>> = new Map();
	let virtual_module_loaded = false;
	let is_dev = false;
	let server: ViteDevServer | null = null;
	let logger: ViteLogger | null = null;
	let css_properties: Set<string> | null = null;
	let resolved_cache_dir: string | null = null;
	let project_root: string | null = null;
	let hmr_timeout: ReturnType<typeof setTimeout> | null = null;
	let last_generated_css: string | null = null;
	let pending_css: string | null = null; // CSS generated during HMR, reused by load()
	/**
	 * Per-file epoch guarding against a deletion (or newer transform) racing an
	 * in-flight transform. `transform()` awaits the disk cache read; an `unlink`
	 * arriving during that await deletes the entry, but the resolved await would
	 * otherwise re-add it and resurrect the deleted file. Captured before the
	 * await, re-checked after.
	 */
	const transform_epochs: Map<string, number> = new Map();
	let epoch_seq = 0;

	/**
	 * Updates detected CSS variables for a file via regex scan against theme variables.
	 * Variables not in the theme are silently ignored (may be user-defined).
	 */
	const update_detected_variables = (id: string, code: string): void => {
		if (!variable_graph) return;
		const theme_var_names = get_all_variable_names(variable_graph);
		const file_vars: Set<string> = new Set();
		for (const name of extract_css_variables(code)) {
			if (theme_var_names.has(name)) {
				file_vars.add(name);
			}
		}
		if (file_vars.size > 0) {
			detected_variables_by_file.set(id, file_vars);
		} else {
			detected_variables_by_file.delete(id);
		}
	};

	// Bundled CSS resources (loaded lazily on first CSS generation when bundled mode is enabled)
	let style_rule_index: StyleRuleIndex | null = null;
	let variable_graph: VariableDependencyGraph | null = null;
	let class_variable_index: CssClassVariableIndex | null = null;

	// Promise for in-flight resource loading (prevents duplicate loads)
	let bundled_resources_promise: Promise<void> | null = null;

	/** Ensures bundled CSS resources are loaded. Safe to call multiple times. */
	const ensure_bundled_resources = async (): Promise<void> => {
		if (style_rule_index !== null) return; // Already loaded
		if (bundled_resources_promise) {
			await bundled_resources_promise; // Wait for in-flight loading
			return;
		}
		bundled_resources_promise = (async () => {
			const resources = await create_bundled_resources({
				base_css,
				variables,
				class_definitions: all_class_definitions,
				deps,
			});
			style_rule_index = resources.style_rule_index;
			variable_graph = resources.variable_graph;
			class_variable_index = resources.class_variable_index;
		})();
		await bundled_resources_promise;
	};

	const log_warn = (msg: string): void => {
		if (logger) {
			logger.warn(msg);
		} else {
			console.warn(msg);
		}
	};

	const log_error = (msg: string): void => {
		if (logger) {
			logger.error(msg);
		} else {
			console.error(msg);
		}
	};

	/**
	 * Generates banner-wrapped CSS from the current classes, dispatching
	 * diagnostics per the `on_error`/`on_warning` settings.
	 */
	const render_css = (): string => {
		const {
			all_classes,
			all_classes_with_locations,
			explicit_classes,
			all_elements,
			explicit_elements,
			explicit_variables,
		} = css_classes.get_all();

		// Aggregate per-file detected CSS variables (already theme-filtered);
		// `generate_css` merges in `explicit_variables`.
		const detected_css_variables: Set<string> = new Set();
		for (const vars of detected_variables_by_file.values()) {
			for (const v of vars) {
				detected_css_variables.add(v);
			}
		}

		const {css: final_css, diagnostics: all_diagnostics} = generate_css({
			all_classes,
			all_classes_with_locations,
			explicit_classes,
			all_elements,
			explicit_elements,
			explicit_variables,
			extraction_diagnostics: css_classes.get_diagnostics(),
			detected_css_variables,
			class_definitions: all_class_definitions,
			interpreters: class_interpreters,
			css_properties,
			include_base,
			include_theme,
			// Resources load lazily; null until ready falls back to utility-only.
			resources:
				style_rule_index && variable_graph && class_variable_index
					? {style_rule_index, variable_graph, class_variable_index}
					: null,
			additional_elements,
			additional_variables,
			exclude_elements,
			exclude_variables,
			theme_specificity,
		});

		// Separate errors and warnings
		const errors = all_diagnostics.filter((d) => d.level === 'error');
		const warnings = all_diagnostics.filter((d) => d.level === 'warning');

		// Handle warnings based on on_warning setting
		if (warnings.length > 0) {
			if (on_warning === 'throw') {
				throw new CssGenerationError(warnings);
			} else if (on_warning === 'log') {
				for (const warning of warnings) {
					log_warn(`[fuz_css] ${format_diagnostic(warning)}`);
				}
			}
			// 'ignore' - do nothing
		}

		// Handle errors based on on_error setting
		if (errors.length > 0) {
			if (on_error === 'throw') {
				throw new CssGenerationError(errors);
			}
			for (const error of errors) {
				log_error(`[fuz_css] ${format_diagnostic(error)}`);
			}
		}

		return `${FUZ_CSS_BANNER}\n\n${final_css}\n\n${FUZ_CSS_BANNER}`;
	};

	/**
	 * Invalidates the virtual module and triggers HMR.
	 * Debounced to avoid spamming updates when multiple files change rapidly.
	 * Only triggers if the generated CSS actually changed.
	 */
	const invalidate_virtual_module = (): void => {
		if (!server) return;

		// Skip HMR if bundled resources aren't loaded yet
		// (will be loaded on first load() call, CSS regenerated then)
		if ((include_base || include_theme) && style_rule_index === null) {
			return;
		}

		if (hmr_timeout) {
			clearTimeout(hmr_timeout);
		}
		hmr_timeout = setTimeout(() => {
			hmr_timeout = null;

			// Check if CSS actually changed
			const new_css = render_css();
			if (new_css === last_generated_css) {
				return; // No change, skip HMR
			}
			last_generated_css = new_css;
			pending_css = new_css; // Store for reuse in load() to avoid regenerating

			const mod = server!.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID_JS);
			if (mod) {
				server!.moduleGraph.invalidateModule(mod);
				// TODO investigate: This hardcoded path matches Vite's URL encoding for virtual
				// modules. Using `mod.url` doesn't work (it's `\0virtual:fuz.css.js`). Could break
				// if Vite changes their encoding scheme. Is there a proper API for this?
				const hmr_path = '/@id/__x00__virtual:fuz.css.js';
				server!.hot.send({
					type: 'update',
					updates: [
						{
							type: 'js-update',
							path: hmr_path,
							acceptedPath: hmr_path,
							timestamp: Date.now(),
						},
					],
				});
			}
		}, HMR_DEBOUNCE_MS);
	};

	return {
		name: 'vite-plugin-fuz-css',
		// Run before other plugins (like Svelte) to see original source files
		enforce: 'pre',

		configResolved(resolved_config) {
			const root = resolved_config.root;
			project_root = root.endsWith('/') ? root : root + '/';
			resolved_cache_dir = join(root, cache_dir);
			logger = resolved_config.logger;
			is_dev = resolved_config.command === 'serve';
		},

		configureServer(dev_server) {
			server = dev_server;
			// Handle file deletion - watcher 'unlink' event
			dev_server.watcher.on('unlink', (file) => {
				// Invalidate any in-flight transform for this file so its post-await
				// re-add can't resurrect the deleted entry.
				transform_epochs.delete(file);
				if (hashes.has(file)) {
					css_classes.delete(file);
					hashes.delete(file);
					detected_variables_by_file.delete(file);

					// Delete cache file (fire and forget)
					if (!is_ci && resolved_cache_dir && project_root) {
						const cache_path = get_file_cache_path(file, resolved_cache_dir, project_root);
						delete_cached_extraction(deps, cache_path).catch(() => {
							// Ignore cache deletion errors
						});
					}

					if (virtual_module_loaded) {
						invalidate_virtual_module();
					}
				}
			});

			// Clean up pending timeout on server close
			dev_server.httpServer?.on('close', () => {
				if (hmr_timeout) {
					clearTimeout(hmr_timeout);
					hmr_timeout = null;
				}
			});
		},

		async buildStart() {
			// Load CSS properties for validation (needed for transform())
			css_properties = await load_css_properties();
			// Note: Bundled CSS resources (style_rule_index, variable_graph, class_variable_index)
			// are loaded lazily on first load() call via ensure_bundled_resources()
		},

		resolveId(id) {
			if (id === VIRTUAL_ID) {
				// In dev mode, resolve to .js for HMR support
				// In build mode, resolve to .css for proper bundling
				return is_dev ? RESOLVED_VIRTUAL_ID_JS : RESOLVED_VIRTUAL_ID_CSS;
			}
			return undefined;
		},

		async load(id) {
			// Dev mode: JS module that injects CSS and handles HMR
			if (id === RESOLVED_VIRTUAL_ID_JS) {
				virtual_module_loaded = true;
				// Defer resource loading to first virtual module access
				if (include_base || include_theme) {
					await ensure_bundled_resources();
				}
				// Use pending CSS from HMR if available, avoiding redundant generation
				const css = pending_css ?? render_css();
				pending_css = null;
				last_generated_css = css; // Track for HMR diffing
				const escaped_css = JSON.stringify(css);
				return `
const css = ${escaped_css};

// Inject CSS on the client only. During SSR (SvelteKit dev prerenders the
// layout that imports this module) document is undefined, so this is a no-op
// on the server; Vite applies styles client-side after hydration.
if (typeof document !== 'undefined') {
  // Find existing style tag or create new one
  let style = document.querySelector('style[data-fuz-css]');
  if (!style) {
    style = document.createElement('style');
    style.setAttribute('data-fuz-css', '');
    document.head.appendChild(style);
  }
  style.textContent = css;
}

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {};
`;
			}
			// Build mode: plain CSS
			if (id === RESOLVED_VIRTUAL_ID_CSS) {
				virtual_module_loaded = true;
				// Defer resource loading to first virtual module access
				if (include_base || include_theme) {
					await ensure_bundled_resources();
				}
				// Emit a marker rule (not a comment — comments are minified away) so
				// generateBundle can find the importer's CSS asset (loaded on every
				// page) and splice the full generated CSS in there.
				return `:root{${FUZ_CSS_PLACEHOLDER}:1}`;
			}
			return undefined;
		},

		generateBundle(_options, bundle) {
			// Regenerate CSS with all extracted classes. Runs after all transforms,
			// so the full set of used classes is available.
			const generated_css = render_css();

			// Splice the generated CSS into the asset that holds the virtual module's
			// placeholder marker. Vite places that marker in the CSS of whatever
			// imported `virtual:fuz.css` (typically the root layout/entry), which is
			// loaded on every page. Appending to an arbitrary "first" CSS asset
			// instead breaks code-split builds (e.g. SvelteKit's per-route CSS):
			// pages that don't load that chunk render completely unstyled.
			let spliced_count = 0;
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css') &&
					chunk.source.includes(FUZ_CSS_PLACEHOLDER)
				) {
					chunk.source =
						chunk.source
							.replace(FUZ_CSS_PLACEHOLDER_DECL_RE, '')
							.replace(FUZ_CSS_PLACEHOLDER_EMPTY_ROOT_RE, '') +
						'\n' +
						generated_css;
					spliced_count++;
				}
			}

			// Normal path: exactly one marked asset, loaded on every page.
			if (spliced_count === 1) return;

			// Marker landed in more than one asset — the full CSS is now duplicated
			// across them. Functional but bloated; surface it rather than ship silently.
			if (spliced_count > 1) {
				log_error(
					`[fuz_css] placeholder marker found in ${spliced_count} CSS assets; generated CSS is` +
						` duplicated across them. Expected a single globally-loaded asset.`,
				);
				return;
			}

			// spliced_count === 0 below: the marker is gone. Only act when the virtual
			// module was actually imported and there's real CSS to deliver — otherwise
			// there's nothing to place (e.g. plugin installed but `virtual:fuz.css`
			// never imported, or a fully empty generation that's only banners).
			if (!virtual_module_loaded) return;
			const has_real_css = generated_css.replaceAll(FUZ_CSS_BANNER, '').trim().length > 0;
			if (!has_real_css) return;

			let css_asset_count = 0;
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css')
				) {
					css_asset_count++;
				}
			}

			// `virtual:fuz.css` was imported but there's nowhere to place its output —
			// every page would render completely unstyled. Fail the build rather than
			// ship a broken artifact (e.g. a config that inlines CSS into JS chunks,
			// where the marker rides in a chunk these asset checks skip).
			if (css_asset_count === 0) {
				throw new Error(
					'[fuz_css] virtual:fuz.css was imported but no CSS asset exists to hold the generated' +
						' styles — every page would be unstyled. Check the build config (cssCodeSplit /' +
						' CSS-in-JS inlining).',
				);
			}

			// Marker stripped but CSS assets exist (e.g. a minifier pruned the unused
			// custom property): append to every one so styles are present on every
			// page. Output may be duplicated; this is a degraded path, so surface it.
			log_error(
				`[fuz_css] placeholder marker not found in any CSS asset (likely stripped by a CSS` +
					` minifier); appending generated CSS to all ${css_asset_count} CSS assets as a` +
					` fallback. Output may be duplicated.`,
			);
			for (const chunk of Object.values(bundle)) {
				if (
					chunk.type === 'asset' &&
					typeof chunk.source === 'string' &&
					chunk.fileName.endsWith('.css')
				) {
					chunk.source = chunk.source + '\n' + generated_css;
				}
			}
		},

		async transform(code, id) {
			// Skip non-matching files
			if (!filter_file(id)) {
				return null;
			}

			// Compute content hash; skip if unchanged
			const hash = hash_blake3(code);
			if (hashes.get(id) === hash) {
				return null;
			}

			const cache_path =
				!is_ci && resolved_cache_dir && project_root
					? get_file_cache_path(id, resolved_cache_dir, project_root)
					: null;

			// Capture an epoch before the (awaiting) cache read so a deletion or
			// newer transform racing the await can be detected after it resolves.
			const epoch = ++epoch_seq;
			transform_epochs.set(id, epoch);

			const {extraction, from_cache, cache_path_to_write} = await extract_file_cached({
				deps,
				content: code,
				content_hash: hash,
				cache_path,
				filename: id,
				acorn_plugins,
			});

			// Bail if the file was deleted or re-transformed during the cache read;
			// re-adding here would resurrect a deleted or stale entry.
			if (transform_epochs.get(id) !== epoch) {
				return null;
			}

			// Log extraction diagnostics (only when freshly parsed; cached diagnostics
			// were already logged on the miss that produced them).
			if (!from_cache && extraction.diagnostics) {
				for (const d of extraction.diagnostics) {
					const loc = `${d.location.file}:${d.location.line}:${d.location.column}`;
					const msg = `[fuz_css] ${loc}: ${d.message}`;
					if (d.level === 'error') {
						log_error(msg);
					} else if (on_warning === 'log') {
						log_warn(msg);
					}
					// 'ignore' and 'throw' (handled at generation time) - don't log here
				}
			}

			// Update CssClasses
			css_classes.add(id, extraction);
			update_detected_variables(id, code);
			hashes.set(id, hash);

			// Save to cache (fire and forget - don't block transform)
			if (cache_path_to_write) {
				save_cached_extraction(deps, cache_path_to_write, hash, extraction).catch(() => {
					// Ignore cache errors
				});
			}

			// Trigger HMR if virtual module already loaded
			if (virtual_module_loaded) {
				invalidate_virtual_module();
			}

			return null;
		},

		// Note: handleHotUpdate not needed - transform hook handles file changes,
		// and configureServer's watcher.on('unlink') handles file deletion
	};
};
