import { test, assert, describe } from 'vitest';
import { resolve } from 'node:path';
import type { GenConfig, GenContext, GenDependenciesResolver } from '@fuzdev/gro/gen.ts';

import { gen_fuz_css } from '#lib/gen_fuz_css.ts';
import type { FileFilter } from '#lib/file_filter.ts';

const ORIGIN_PATH = 'src/routes/fuz.gen.css.ts';
const OWN_BANNER = `/* generated by ${ORIGIN_PATH} */`;

interface StubFile {
	id: string;
	contents: string;
}

// the slice of Gro's filer the generator reads
const create_stub_filer = (files: Array<StubFile> = []) => {
	const disknodes = new Map(
		files.map((f) => [f.id, { ...f, external: false, content_hash: `hash:${f.contents}` }])
	);
	return { files: disknodes, get_by_id: (id: string) => disknodes.get(id), init: async () => {} };
};

const create_dependencies_context = (changed_file_id: string, files?: Array<StubFile>) =>
	({
		changed_file_id,
		filer: create_stub_filer(files),
		origin_path: ORIGIN_PATH
	}) as unknown as GenContext;

// the dependency resolver of a generator, which judges a changed file through the filter
const resolve_dependencies = (filter_file: FileFilter, project_root?: string) => {
	const gen = gen_fuz_css({ filter_file, project_root }) as GenConfig;
	const dependencies = gen.dependencies as GenDependenciesResolver;
	return (changed_file_id: string) => dependencies(create_dependencies_context(changed_file_id));
};

const noop = (): void => {};

// runs a generator over stub CSS files, which never touch the extraction cache
const generate = async (root: string, files: Array<StubFile>): Promise<string> => {
	const gen = gen_fuz_css({ project_root: root }) as GenConfig;
	return (await gen.generate({
		filer: create_stub_filer(files),
		log: { info: noop, warn: noop, error: noop },
		origin_path: ORIGIN_PATH
	} as unknown as GenContext)) as string;
};

describe('gen_fuz_css', () => {
	test('the filter receives the project root, resolved to an absolute path', async () => {
		const calls: Array<[string, string]> = [];
		const spy: FileFilter = (path, root) => {
			calls.push([path, root]);
			return true;
		};
		await resolve_dependencies(spy, 'some/app')('/abs/some/app/src/a.ts');
		assert.deepEqual(calls, [['/abs/some/app/src/a.ts', resolve('some/app')]]);
	});

	test('the default filter judges a project under a test directory by its own paths', async () => {
		const root = '/srv/test/app';
		const gen = gen_fuz_css({ project_root: root }) as GenConfig;
		const dependencies = gen.dependencies as GenDependenciesResolver;
		const changed = (id: string) => dependencies(create_dependencies_context(id));
		assert.strictEqual(await changed(`${root}/src/App.svelte`), 'all');
		assert.isNull(await changed(`${root}/src/test/App.svelte`));
		assert.isNull(await changed(`${root}/notes.md`));
	});

	test('a CSS file triggers the generator, but not its own output', async () => {
		const root = '/srv/app';
		const gen = gen_fuz_css({ project_root: root }) as GenConfig;
		const dependencies = gen.dependencies as GenDependenciesResolver;
		const files = [
			{ id: `${root}/src/app.css`, contents: 'a { color: var(--palette_d_50); }' },
			{ id: `${root}/src/routes/fuz.css`, contents: `${OWN_BANNER}\n\n:root {}` }
		];
		const changed = (id: string) => dependencies(create_dependencies_context(id, files));
		assert.strictEqual(await changed(`${root}/src/app.css`), 'all');
		assert.isNull(await changed(`${root}/src/routes/fuz.css`));
	});

	test("a CSS file's variable references are included", async () => {
		const root = '/srv/app';
		const css = await generate(root, [
			{ id: `${root}/src/app.css`, contents: 'a { color: var(--palette_d_50); }' }
		]);
		assert.include(css, '--palette_d_50:');
	});

	test("the generator's own output doesn't feed its variables back in", async () => {
		const root = '/srv/app';
		const css = await generate(root, [
			{
				id: `${root}/src/routes/fuz.css`,
				contents: `${OWN_BANNER}\n\na { color: var(--palette_d_50); }`
			}
		]);
		assert.notInclude(css, '--palette_d_50:');
	});
});
