<script lang="ts">
	import Code from '@fuzdev/fuz_code/Code.svelte';
	import TomeContent from '@fuzdev/fuz_ui/TomeContent.svelte';
	import TomeSection from '@fuzdev/fuz_ui/TomeSection.svelte';
	import TomeSectionHeader from '@fuzdev/fuz_ui/TomeSectionHeader.svelte';
	import MdnLink from '@fuzdev/fuz_ui/MdnLink.svelte';
	import {get_tome_by_name} from '@fuzdev/fuz_ui/tome.js';
	import TomeLink from '@fuzdev/fuz_ui/TomeLink.svelte';

	import ModuleLink from '$routes/ModuleLink.svelte';
	import FileLink from '$routes/FileLink.svelte';
	import Introduction from '$routes/Introduction.svelte';

	const LIBRARY_ITEM_NAME = 'introduction';

	const tome = get_tome_by_name(LIBRARY_ITEM_NAME);
</script>

<TomeContent {tome}>
	<section>
		<Introduction />
		<TomeSection>
			<TomeSectionHeader text="Usage" />
			<Code lang={null} content="npm i -D @fuzdev/fuz_css" />
			<p>Import the two required stylesheets:</p>
			<Code
				lang="ts"
				content={`import '@fuzdev/fuz_css/style.css';
import '@fuzdev/fuz_css/theme.css'; // or bring your own`}
			/>
			<p>
				For utility classes, see the <TomeLink name="classes" /> reference which covers the Vite plugin
				and alternative Gro generator.
			</p>
		</TomeSection>
		<TomeSection>
			<TomeSectionHeader text="Details" />
			<ul>
				<li>plain CSS</li>
				<li>minimal dependencies, all optional -- none needed if you only use the stylesheets</li>
				<li>
					exports a reset stylesheet with <TomeLink name="semantic" /> defaults that styles HTML elements,
					see <ModuleLink path="style.css" />
				</li>
				<li>
					supports <TomeLink name="themes" /> a basic theme stylesheet, <ModuleLink
						path="theme.css"
					/>, that can be replaced with your own
				</li>
				<li>also exports the underlying CSS data, helpers, and types for open-ended usage</li>
				<li>
					uses its own concept of style <TomeLink name="variables" />, a specialization of CSS
					custom properties and design tokens
					<ul>
						<li>variables are the main source of truth and are used in the main stylesheet</li>
						<li>each variable provides values to light and/or dark mode</li>
						<li>includes optional utility classes that use the variables</li>
					</ul>
				</li>
				<li>themes are groups of variables</li>
				<li>
					dark mode is a first-class concept in the system, not a theme; instead, each theme can
					support light and/or dark <MdnLink path="Web/CSS/color-scheme">color-schemes</MdnLink>
				</li>
				<li>
					supports optional <TomeLink name="classes">utility classes</TomeLink> with three types (token,
					composite, CSS-literal) and modifiers for responsive, state, color-scheme, and pseudo-elements
				</li>
				<li>
					the stylesheets work with any framework and plain HTML; utility class generation supports
					Svelte, JSX, and TypeScript/JS -- see
					<TomeLink name="classes" hash="Framework-support">framework support</TomeLink> and
					<a href="https://ui.fuz.dev/docs/Themed"><code>Themed</code></a> in
					<a href="https://ui.fuz.dev/">fuz_ui</a> for Svelte integration
				</li>
				<li>
					see the <TomeLink name="classes" hash="Compared-to-alternatives"
						>comparison to alternatives</TomeLink
					> to understand fuz_css relative to TailwindCSS and UnoCSS
				</li>
			</ul>
			<p>The stylesheets:</p>
			<ul>
				<li>
					<ModuleLink path="style.css" /> -- reset stylesheet with semantic defaults
				</li>
				<li>
					<ModuleLink path="theme.css" /> -- or bring your own
				</li>
				<li>
					<FileLink path="src/routes/fuz.css">src/routes/fuz.css</FileLink> -- the generated file for
					this docs website, using fuz_css's helpers that includes only the utility classes your code
					uses, generated by
					<a href="https://github.com/ryanatkn/gro">Gro</a> with <FileLink
						path="src/routes/fuz.gen.css.ts">src/routes/fuz.gen.css.ts</FileLink
					> using the fuz_css helpers in
					<ModuleLink path="gen_fuz_css.js" />. There's also a <ModuleLink
						path="vite_plugin_fuz_css.js"
					/> for non-SvelteKit projects -- see the <TomeLink name="examples" /> page.
				</li>
				<li>
					There are not yet tools for optimizing away unused variables or main stylesheet rulesets,
					so <code>style.css</code>
					and
					<code>theme.css</code> have some bloat, but at ~750 and ~500 lines they're not huge.
				</li>
			</ul>
			<p>
				In the docs, you'll see <code>⚠️ asides</code> with open questions and other uncertainties
				as fuz_css evolves towards v1. Your input is appreciated in the GitHub
				<a href="https://github.com/fuzdev/fuz_css/issues">issues</a> and
				<a href="https://github.com/fuzdev/fuz_css/discussions">discussions</a> 🌿
			</p>
		</TomeSection>
	</section>
</TomeContent>
