<script lang="ts">
	import TomeContent from '@fuzdev/fuz_ui/TomeContent.svelte';
	import MdnLink from '@fuzdev/fuz_ui/MdnLink.svelte';
	import {get_tome_by_name} from '@fuzdev/fuz_ui/tome.js';

	import ModuleLink from '$routes/ModuleLink.svelte';
	import FileLink from '$routes/FileLink.svelte';
	import Introduction from '$routes/Introduction.svelte';

	const LIBRARY_ITEM_NAME = 'introduction';

	const tome = get_tome_by_name(LIBRARY_ITEM_NAME);
</script>

<TomeContent {tome}>
	<section>
		<Introduction />
		<p>Details:</p>
		<ul>
			<li>plain CSS</li>
			<li>zero dependencies</li>
			<li>
				exports a reset stylesheet (<ModuleLink path="style.css" />) with semantic defaults that
				styles HTML elements
			</li>
			<li>
				exports a basic theme stylesheet (<ModuleLink path="theme.css" />) that can be replaced with
				your own
			</li>
			<li>
				also exports the underlying CSS data, helpers, and types, which can be used in many ways,
				including outputting an optimized utilities class file
			</li>
			<li>
				uses its own concept of style variables, a specialization of CSS custom properties and
				design tokens
				<ul>
					<li>variables are the main source of truth</li>
					<li>each variable provides values to light and/or dark mode</li>
					<li>includes optional utility and component classes that use the variables</li>
				</ul>
			</li>
			<li>themes are groups of variables</li>
			<li>
				dark mode is a first-class concept in the system, not a theme, instead each theme can
				support light and/or dark <MdnLink path="Web/CSS/color-scheme">color-schemes</MdnLink>
			</li>
			<li>
				is agnostic to JS frameworks, for example usage see <a href="https://ui.fuz.dev/docs/Themed"
					><code>Themed</code></a
				>
				in my Svelte UI library <a href="https://ui.fuz.dev/">Fuz UI</a>
			</li>
		</ul>
		<p>The stylesheets:</p>
		<ul>
			<li>
				<ModuleLink path="style.css" /> - reset stylesheet with semantic defaults
			</li>
			<li>
				<ModuleLink path="theme.css" /> - or bring your own
			</li>
			<li>
				<FileLink path="src/routes/fuz.css">src/routes/fuz.css</FileLink> - a generated reference implementation
				using Fuz CSS's helpers that includes only the utility classes your code uses, generated by
				<a href="https://github.com/ryanatkn/gro">Gro</a> with <FileLink
					path="src/routes/fuz.gen.css.ts">src/routes/fuz.gen.css.ts</FileLink
				> using the Fuz CSS helpers in
				<ModuleLink path="gen_fuz_css.js" />. I can add a Vite plugin if there's demand.
			</li>
			<li>
				There are not yet tools for optimizing away unused variables, so <code>style.css</code> and
				<code>theme.css</code> have some bloat.
			</li>
		</ul>
		<p>
			In the docs, you'll see <code>⚠️ asides</code> with open questions and other uncertainties.
			Your input is appreciated in the GitHub
			<a href="https://github.com/fuzdev/fuz_css/issues">issues</a> and
			<a href="https://github.com/fuzdev/fuz_css/discussions">discussions</a> 🌿
		</p>
	</section>
</TomeContent>
